=== navikt/melosys-web-mock/scripts/schema/journalforing-tilordne-schema.json
{
  "$id": "/tilordne",
  "type": "object",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "The Root Schema",
  "additionalProperties": false,
  "required": [
    "journalpostID",
    "oppgaveID",
    "brukerID",
    "dokumenttittel",
    "vedleggstitler",
    "saksnummer"
  ],
  "properties": {
    "journalpostID": {
      "$id": "/properties/journalpostID",
      "type": "string",
      "title": "The Journalpostid Schema ",
      "default": "",
      "examples": [
        "DOK_321"
      ]
    },
    "oppgaveID": {
      "$id": "/properties/oppgaveID",
      "type": "string",
      "title": "The Oppgaveid Schema ",
      "default": "",
      "examples": [
        "192121803"
      ]
    },
    "brukerID": {
      "$id": "/properties/brukerID",
      "type": "string",
      "title": "The Brukerid Schema ",
      "default": "",
      "examples": [
        "30098000492"
      ]
    },
    "avsenderID": {
      "$id": "/properties/avsenderID",
      "type": "string",
      "title": "The Avsenderid Schema ",
      "default": "",
      "examples": [
        "30098000492"
      ]
    },
    "avsenderNavn": {
      "$id": "#/properties/avsenderNavn",
      "type": "string",
      "title": "The avsenderNavn Schema",
      "default": "",
      "examples": [
        "30098000492"
      ],
      "pattern": "^(.*)$"
    },
    "dokumentID": {
      "$id": "#/properties/dokumentID",
      "type": "string",
      "title": "The dokumentID Schema",
      "default": "",
      "examples": [
        "30098000492"
      ],
      "pattern": "^(.*)$"
    },
    "dokumenttittel": {
      "$id": "/properties/dokumenttittel",
      "type": "string",
      "title": "The Dokumenttittel Schema ",
      "default": "",
      "examples": [
        "SÃ¸knad om medlemskap"
      ]
    },
    "vedleggstitler": {
      "$id": "/properties/vedleggstitler",
      "type": "array",
      "items": {
        "$id": "/properties/vedleggstitler/items",
        "type": "string"
      }
    },
    "saksnummer": {
      "$id": "/properties/saksnummer",
      "type": "string",
      "title": "The Saksnummer Schema ",
      "default": 0,
      "examples": [
        44
      ]
    }
  }
}

=== navikt/melosys-web-mock/scripts/mock_data/journalforing/post/tilordne.json
{
  "saksnummer": "MELTEST-1",
  "avsenderID": "30098000492",
  "avsenderNavn": "PEN FUL",
  "brukerID": "30098000492",
  "dokumentID": "Dok_ID",
  "dokumenttittel": "SÃ¸knad om medlemskap",
  "journalpostID": "DOK_321",
  "oppgaveID": "177057928",
  "vedleggstitler": [
    "Vedleggstittel 1"
  ]
}
