=== navikt/melosys-web-mock/scripts/schema/organisasjoner-schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://melosys.nav.no/schemas/organisasjoner-schema.json",
  "type": "object",
  "title": "The Root Schema",
  "additionalProperties": false,
  "required": [
    "orgnr",
    "oppstartdato",
    "postadresse",
    "organisasjonsform",
    "navn",
    "forretningsadresse"
  ],
  "properties": {
    "orgnr": {
      "$id": "#/properties/orgnr",
      "type": "string",
      "title": "The Orgnr Schema",
      "default": "",
      "examples": [
        "910099035"
      ],
      "pattern": "^(.*)$"
    },
    "oppstartdato": {
      "$id": "#/properties/oppstartdato",
      "title": "The Oppstartdato Schema",
      "$ref": "http://melosys.nav.no/schemas/definitions-schema.json#/definitions/nullable-dato"
    },
    "postadresse": {
      "$id": "#/properties/postadresse",
      "title": "The Postadresse Schema",
      "$ref": "http://melosys.nav.no/schemas/definitions-schema.json#/definitions/strukturertadresse"
    },
    "organisasjonsform": {
      "$id": "#/properties/organisasjonsform",
      "type": [
        "string",
        "null"
      ],
      "title": "The Organisasjonsform Schema",
      "default": null,
      "examples": [
        null
      ]
    },
    "navn": {
      "$id": "#/properties/navn",
      "type": "string",
      "title": "The Navn Schema",
      "default": "",
      "examples": [
        "SKARSVÃ…G OG VANSE"
      ],
      "pattern": "^(.*)$"
    },
    "forretningsadresse": {
      "$id": "#/properties/forretningsadresse",
      "title": "The Forretningsadresse Schema",
      "$ref": "http://melosys.nav.no/schemas/definitions-schema.json#/definitions/strukturertadresse"
    }
  }
}

=== navikt/melosys-web-mock/scripts/mock_data/organisasjoner/orgnr-910253158.json
{
  "orgnr": "910253158",
  "navn": "MULTICONSULT ASA",
  "oppstartdato" : null,
  "forretningsadresse": {
    "gateadresse": {
      "gatenummer" : null,
      "husbokstav" : null,
      "husnummer" : null,
      "gatenavn": "Nedre Skøyen vei 2"
    },
    "postnr": "0276",
    "poststed": "OSLO",
    "land": "NORGE"
  },
  "organisasjonsform" : null,
  "postadresse": {
    "gateadresse": {
      "gatenummer" : null,
      "husbokstav" : null,
      "husnummer" : null,
      "gatenavn": "Postboks 265  Skøyen"
    },
    "postnr": "0213",
    "poststed": "OSLO",
    "land": "NORGE"
  }
}

=== navikt/melosys-web-mock/scripts/mock_data/organisasjoner/orgnr-923609016.json
{
  "orgnr": "923609016",
  "navn": "EQUINOR ASA",
  "oppstartdato" : null,
  "forretningsadresse": {
    "gateadresse": {
      "gatenummer" : null,
      "husbokstav" : null,
      "husnummer" : null,
      "gatenavn": "Forusbeen 50"
    },
    "postnr": "4035",
    "poststed": "STAVANGER",
    "land": "NORGE"
  },
  "organisasjonsform" : null,
  "postadresse": {
    "gateadresse": {
      "gatenummer" : null,
      "husbokstav" : null,
      "husnummer" : null,
      "gatenavn": "Postboks 8500"
    },
    "postnr": "4035",
    "poststed": "STAVANGER",
    "land": "NORGE"
  }
}

=== navikt/melosys-web-mock/scripts/mock_data/organisasjoner/orgnr-912499693.json
{
  "orgnr": "912499693",
  "navn": "TOP-TOY NORGE AS AVD HOVEDKONTOR",
  "oppstartdato" : null,
  "forretningsadresse": {
    "gateadresse": {
      "gatenummer" : null,
      "husbokstav" : "C",
      "husnummer" : 1,
      "gatenavn": "Pindsleveien 1C"
    },
    "postnr": "3221",
    "poststed": "SANDEFJORD",
    "land": "NORGE"
  },
  "organisasjonsform" : null,
  "postadresse": {
    "gateadresse": {
      "gatenummer" : null,
      "husbokstav" : null,
      "husnummer" : null,
      "gatenavn": "Postboks 2044 SANDEFJORD"
    },
    "postnr": "3221",
    "poststed": "SANDEFJORD",
    "land": "NORGE"
  }
}

=== navikt/melosys-web-mock/scripts/mock_data/organisasjoner/orgnr-967032271.json
{
  "orgnr": "967032271",
  "navn": "SWECO NORGE AS",
  "oppstartdato" : null,
  "forretningsadresse": {
    "gateadresse": {
      "gatenummer" : null,
      "husbokstav" : null,
      "husnummer" : null,
      "gatenavn": "Drammensveien 260"
    },
    "postnr": "0283",
    "poststed": "OSLO",
    "land": "NORGE"
  },
  "organisasjonsform" : null,
  "postadresse": {
    "gateadresse": {
      "gatenummer" : null,
      "husbokstav" : null,
      "husnummer" : null,
      "gatenavn": "Postboks 80   Sk√∏yen"
    },
    "postnr": "0212",
    "poststed": "OSLO",
    "land": "NORGE"
  }
}

=== navikt/melosys-web-mock/scripts/mock_data/organisasjoner/orgnr-873152362.json
{
  "orgnr": "873152362",
  "navn": "EQUINOR ASA AVD KONTOR BERGEN",
  "oppstartdato" : null,
  "forretningsadresse": {
    "gateadresse": {
      "gatenummer" : null,
      "husbokstav" : null,
      "husnummer" : null,
      "gatenavn": "Sandslivegen 90"
    },
    "postnr": "5254",
    "poststed": "BERGEN",
    "land": "NORGE"
  },
  "organisasjonsform" : null,
  "postadresse": {
    "gateadresse": {
      "gatenummer" : null,
      "husbokstav" : null,
      "husnummer" : null,
      "gatenavn": "Postboks 7200 BERGEN"
    },
    "postnr": "5254",
    "poststed": "BERGEN",
    "land": "NORGE"
  }
}

=== navikt/melosys-web-mock/scripts/mock_data/organisasjoner/orgnr-910099035.json
{
  "orgnr": "910099035",
  "navn": "SKARSVÃ…G OG VANSE",
  "oppstartdato" : null,
  "forretningsadresse": {
    "gateadresse": {
      "gatenummer" : null,
      "husbokstav" : null,
      "husnummer" : null,
      "gatenavn": "Olav Kyrres gate 9"
    },
    "postnr": "3936",
    "poststed": "TRONDHEIM",
    "land": "NORGE"
  },
  "organisasjonsform" : null,
  "postadresse": {
    "gateadresse": {
      "gatenummer" : null,
      "husbokstav" : null,
      "husnummer" : null,
      "gatenavn": "Olav Kyrres gate 9"
    },
    "postnr": "3936",
    "poststed": "TRONDHEIM",
    "land": "NORGE"
  }
}
